### ISSUE TITLE
Do not fork from my projects ;)

### ISSUE THREAD

**Issue by zerothi** [tomato151/test#1]
Hi @tomato151

I see you are forking lots of my repositories. You are doing it wrong ;)

- https://github.com/tomato151/sisl forked from tfrederiksen/sisl
- numpy, scipy, matplotlib and phonopy you have forked from zerothi/*

Unless you are collaborating with people on a fork of the original project then you should never fork users repositories. Instead fork their original repositories numpy/numpy, scipy/scipy matplotlib/matplotlib phonopy/phonopy zerothi/sisl etc.

I don't know how to contact you otherwise, hence this issue here.

**Comment by tomato151** [comment]
Hi， @zerothi  
I’m so sorry for doing the wrong things. I have deleted the corresponding  repositories.

**Comment by zerothi** [comment]
No worries, it was just for your information. :)
